import fs from "node:fs";
import path from "node:path";

import { log } from "../log.js";
import { toolPaths } from "../paths.js";

/**
 * Recursively copies a directory, creating parent directories as needed.
 * Used to copy the Neovim theme structure (colors/ and lua/) into the config.
 */
const copyDir = (src: string, dest: string): void => {
  fs.mkdirSync(dest, { recursive: true });

  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);

    if (entry.isDirectory()) {
      copyDir(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  }
};

/**
 * Installs the Scalar colorscheme for Neovim.
 *
 * Copies colorscheme files into ~/.config/nvim/colors/ and the lualine
 * theme into ~/.config/nvim/lua/lualine/themes/. This works with both
 * standard Neovim and LazyVim -- no plugin manager configuration needed.
 *
 * After install, set your colorscheme with:
 *   :colorscheme scalar
 * Or in LazyVim:
 *   opts = { colorscheme = "scalar" }
 */
export const installNeovim = (): void => {
  const { configDir, source } = toolPaths.neovim;

  if (!fs.existsSync(configDir)) {
    log.warn("Neovim config directory not found");
    log.dim(`Expected: ${configDir}`);
    log.dim("Create it and run this command again.");
    return;
  }

  /** Copy colors/ directory (scalar.lua, scalar-dark.lua, scalar-light.lua) */
  const colorsSource = path.join(source, "colors");
  const colorsDest = path.join(configDir, "colors");
  copyDir(colorsSource, colorsDest);

  const colorFiles = fs.readdirSync(colorsSource).filter((f) => f.endsWith(".lua"));
  log.ok(`Copied ${String(colorFiles.length)} colorscheme files to ${colorsDest}`);

  /** Copy lua/lualine/themes/ for lualine integration */
  const lualineSource = path.join(source, "lua", "lualine", "themes");
  const lualineDest = path.join(configDir, "lua", "lualine", "themes");

  if (fs.existsSync(lualineSource)) {
    copyDir(lualineSource, lualineDest);
    log.ok("Copied lualine theme");
  }

  /**
   * Try to auto-configure LazyVim if the user has the standard LazyVim
   * plugin config structure. We write a small plugin spec that sets the
   * colorscheme to "scalar".
   */
  const pluginsDir = path.join(configDir, "lua", "plugins");
  const specPath = path.join(pluginsDir, "scalar-theme.lua");

  if (fs.existsSync(pluginsDir)) {
    const spec = [
      "-- Scalar colorscheme configuration (auto-generated by scalar-themes)",
      "-- Delete this file to stop using the Scalar theme.",
      "return {",
      '  { "LazyVim/LazyVim", opts = { colorscheme = "scalar" } },',
      "}",
      "",
    ].join("\n");

    fs.writeFileSync(specPath, spec, "utf-8");
    log.ok("Created LazyVim plugin spec");
    log.dim(specPath);
  } else {
    log.dim('Set colorscheme with: vim.cmd.colorscheme("scalar")');
    log.dim('Or in LazyVim: opts = { colorscheme = "scalar" }');
  }
};
